# Generated by Django 5.1.15 on 2026-08-26 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(db_index=True)),
                ('model_name', models.CharField(default='EnsembleQuantileRegressor', max_length=100)),
                ('model_version', models.CharField(default='v1.0.0', max_length=50)),
                ('horizon_days', models.IntegerField(default=5)),
                ('sample_size', models.IntegerField(default=0)),
                ('baseline_mae', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('model_mae', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('directional_accuracy', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('features_used', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-run_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_days', models.IntegerField(default=5)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_price_mean', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_price_lower', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_price_upper', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_return_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('prob_positive', models.DecimalField(decimal_places=4, max_digits=6)),
                ('confidence_label', models.CharField(choices=[('HIGH', 'High Confidence'), ('MEDIUM', 'Medium Confidence'), ('LOW', 'Low Confidence')], default='MEDIUM', max_length=20)),
                ('baseline_mae', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('model_mae', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('directional_accuracy', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('model_version', models.CharField(default='v1.0.0', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='stocks.stock')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='forecasts.forecastrun')),
            ],
            options={
                'ordering': ['-generated_at', 'horizon_days'],
                'indexes': [models.Index(fields=['stock', 'horizon_days'], name='forecasts_f_stock_i_cf4b60_idx')],
            },
        ),
    ]
