# Generated by Django 5.1.15 on 2026-08-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Market Indices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SectorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100, unique=True)),
                ('change_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('top_gainer', models.CharField(blank=True, max_length=50, null=True)),
                ('top_loser', models.CharField(blank=True, max_length=50, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-change_percent'],
            },
        ),
    ]
