# Generated by Django 4.2.3 on 2024-11-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_trendingstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingstock',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
