# Generated by Django 4.2.3 on 2025-10-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_trendingstock_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='TrendingStock',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.AddField(
            model_name='stock',
            name='date_of_listing',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='isin_number',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='series',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
