# Generated by Django 4.2.3 on 2025-10-27 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_sectors_delete_option_delete_trendingstock_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sectors',
            new_name='Sector',
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_of_listing',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='isin_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='series',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
