# Generated by Django 4.2.3 on 2025-10-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_rename_sectors_sector_alter_stock_date_of_listing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock',
            name='isin_number',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
