# Generated by Django 4.2.25 on 2025-11-16 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_remove_stock_id_alter_stock_isin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='sector_name_dashed',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
