# Generated by Django 4.2.25 on 2025-11-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_sector_sector_name_dashed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='sector_name_dashed',
        ),
    ]
