# Generated by Django 5.1.15 on 2026-08-26 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('rsi_14', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('macd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('macd_signal', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('macd_hist', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('sma_20', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sma_50', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sma_200', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ema_20', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('atr_14', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('upper_band', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lower_band', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('signal_summary', models.CharField(default='NEUTRAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_indicators', to='stocks.stock')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', 'date'], name='technicals__stock_i_deae0b_idx')],
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='unique_stock_indicator_date')],
            },
        ),
    ]
