# Generated by Django 5.1.15 on 2026-08-26 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('exchange', models.CharField(default='NSE', max_length=20)),
                ('sector', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('day_change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('day_change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='stocks_stoc_symbol_3e1bfd_idx'), models.Index(fields=['sector'], name='stocks_stoc_sector_6c2055_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockFundamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pb_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('week_52_high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('week_52_low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundamentals', to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stock')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', 'date'], name='stocks_stoc_stock_i_86bebf_idx')],
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='unique_stock_price_date')],
            },
        ),
    ]
